---
title: Analysis of Education Expenditures and Standardized Test Scores
author: by Kathleen, Thomas, Meg, and Dieter
output: github_document
---

## Summary
Our aim in this project was to search for relationships between expenditure, revenue, and standardized test scores in the United States. We planned to find out if different kinds of expenditure have notable effects on test scores, as well as how expenditure per student affects test scores. While standardized test scores are not the most holistic approach to gauging academic success in a school district or state, these scores are the most objective and accessible gauges of measurement to use in a study of this nature. We approached this analysis from several angles, creating visualizations that address each state within them, as well as narrowing in on specific locations. We began our exploration with the creation of a correlation matrix, continuing on to create a visualization of the state average reading scores by year. Washington D.C. stood out in this visualization for consistently having much lower scores than other states, which led to a deeper dive into the city’s scores and total revenue. We proceeded to investigate a possible relationship between expenditure per student and test scores, which is visualized in a plot as well as a map. Visualizations of support services expenditure as well as instruction expenditure did not prove to have any correlation to an increase in test scores. 

## Results and Discussion
We found that there is a positive correlation between school expenditure and the test scores of students. The relationship, however, is not linear. At relatively low per-student expenditures, we find that increasing per-student expenditure results in a larger proportional increase in student test scores. There appears to be an inflection point that occurs after the national average, the national average total expenditure per student is $13,187. At which point, increasing per student expenditure has a drastically reduced impact on student test scores. It is important to note that this result is true if we do not include the District of Columbia in our calculations. D.C., as a result of its unique circumstances, such as its considerably lower number of schools and the urban nature of its school districts, is a true outlier. By including D.C in our data analysis, we see that the increase in spending per student, beyond the national average, actually has a negative correlation with test scores. The maps presented help to visualize these disparities in national test score distributions as well as national school expenditure distributions. It is important to note the inherent limitations of our data sets and the conclusions we present. D.C is illustrative of the fact that the demographics and economic factors of a region play a considerable role in the performance of students. These factors are intrinsically linked to the data we present, as such, while we do argue that there is a correlation between student expenditure and student performance, the data we have does not allow us to rule out or quantify the impact these other factors have. Hence, we recognize that correlation does not imply causation and we advocate for a more comprehensive analysis of how some of the mitigating factors mentioned above impact student performance. 

In order to further investigate the impact of demographics and economic factors on the test scores of students, a more in depth data analysis could be done that includes a regional analysis of total expenditure vs. average test scores in each state. This regional analysis would give a better understanding of which areas in each state have stronger correlations between total expenditure and test scores. To get an even closer look at the different factors that drive the differing correlations per region, an analysis on neighborhoods per region could be done to investigate the effect of neighborhood demographics, neighborhood average income, and average number of kids per family in each neighborhood in the region on student performance. Student test scores are inevitably influenced by a number of factors aside from state expenditure, which is why taking a more holistic approach to the data analysis that includes data on regional and neighborhood levels could provide more insight to factors that could be affecting student performance and student test scores, including racial and ethnic demographics in neighborhoods, neighborhood income, and family dynamics, which could be affected by the resources families have access to and the amount of kids that they need to provide those resources to. The total expenditure per student map of the U.S. shows that the highest median expenditure was in New York, Vermont, New Jersey, Wyoming, and Alaska. The lowest median expenditure in Arizona, Utah, and Idaho. This map is interesting because statistically California has the highest expenditure, followed by New York, Texas and Pennsylvania (statista data set), which are not the highest displayed on the map. The states that showed the highest positive correlation between total expenditure per student and average test scores were Wyoming, Vermont, New Jersey. 




## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data 

The dataset used in this presentation is found in the website, Kaggle and it is named “U.S. Education Datasets: Unification Project”. This dataset is a combination of three different sources: the National Center for Education Statistics, the United States Census Bureau, and The Nation's Report Card. This dataset has an extensive amount of information that allows us to explore different aspects of education, more specifically how, and if, the total expenditure of states for schools affected the scores of its students. This was possible due to the fact that the dataset contains information from all 50 states regarding the total expenditure of each state and their average test scores.  The average scores were obtained by the National Assessment of Education Progress, also known as NAEP. It is important to note that the average test score is an estimate gathered from a representative sample of students in both public and nonpublic schools rather than all the student population. With this information, the group was able to look at different statistical analyses of the data to help us answer our question.

#Kaggle dataset
Garrard, Roy. “U.S. Education Datasets: Unification Project.” Kaggle, 13 Apr. 2020, https://www.kaggle.com/noriuk/us-education-datasets-unification-project.

Data is sourced from the U.S. Census Bureau and the National Center for Education Statistics (NCES).
# Enrollment
https://nces.ed.gov/ccd/stnfis.asp
# Financials
https://www.census.gov/programs-surveys/school-finances/data/tables.html
# Academic Achievement
https://www.nationsreportcard.gov/ndecore/xplore/NDE




## References

Garrard, Roy. “U.S. Education Datasets: Unification Project.” Kaggle, 13 Apr. 2020, https://www.kaggle.com/noriuk/us-education-datasets-unification-project.


