---
title: "Project Proposal"
name: "Thomas, Kathleen, Dieter, Meg"
date: "10/10/2021"
output: html_document
---

## Introduction 

  In this project, we aim to gauge the relationship between state revenue, education expenditure, and standardized test scores. We plan to narrow in on states and cities that present unique or helpful information, as well as the different kinds of expenditure used to support school systems and students. Our dataset is from Kaggle, titled "U.S. Education Datasets: Unification Project. This dataset is a compilation of K-12 financial data, enrollment, and achievement sourced from the U.S. Census Bureau, the National Center for Education Statistics, and The Nation's Report Card. The cases in this dataset are the students whose standardized test scores are being recorded, this data is collected annually by school districts nationwide and communicated to state and national education bureaus to keep track of yearly academic progress and shortcomings. 

  The contextual variables involved in this dataset are the state the data pertains to, the year it was collected, and the number of kids enrolled in K-12 schooling in the given state. The revenue related variables include the state's total revenue (summary of federal, local, and state revenues), as well as individual variables for the state's federal revenue, the state's revenue, and the state's local revenue. Expenditure variables include instruction expenditure, support services expenditure, capital outlay expenditure, and other expenditure. We will be analyzing a few of these different kinds of spending in hopes of finding a specific kind of expenditure that proves to be more helpful in raising test scores. The assessment related variables come from results of the annually administered National Exam of Educational Progress. These include mean scores of 4th grade math tests, 8th grade math tests, 4 grade reading tests, and 8th grade reading tests. 


## Data Set Overview

```{r}
#install.packages("dplyr")
library(tidyverse)
```




## Data Analysis Plan

## Works Cited




